/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bancoswing;

import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Lemke
 */
public class ContaCadastro extends javax.swing.JFrame {

    private final String conta_corrente = "Corrente";
    private final String conta_investimento = "Investimento";

    /**
     * Creates new form ContaCadastro
     */
    public ContaCadastro() {
        initComponents();
        Limpa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtContaCpf = new javax.swing.JTextField();
        btContaBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtContaNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbContaTipo = new javax.swing.JComboBox();
        btContaSalvar = new javax.swing.JButton();
        btContaCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtContaDeposito = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtContaLimite = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtContaMontante = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtContaDepositoMin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cadastro de Conta");
        setBounds(new java.awt.Rectangle(200, 100, 0, 0));

        jLabel4.setText("CPF:");

        btContaBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ic_search_black_18dp_1x.png"))); // NOI18N
        btContaBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContaBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        txtContaNome.setEnabled(false);

        jLabel5.setText("Tipo de Conta:");

        cbContaTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Corrente", "Investimento" }));
        cbContaTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbContaTipoItemStateChanged(evt);
            }
        });

        btContaSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ic_save_black_18dp_1x.png"))); // NOI18N
        btContaSalvar.setText("Salvar");
        btContaSalvar.setEnabled(false);
        btContaSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContaSalvarActionPerformed(evt);
            }
        });

        btContaCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ic_cancel_black_18dp_1x.png"))); // NOI18N
        btContaCancelar.setText("Cancelar");
        btContaCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContaCancelarActionPerformed(evt);
            }
        });

        jLabel2.setText("Depósito Inicial: ");

        txtContaDeposito.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtContaDeposito.setText("0,00");

        jLabel3.setText("Limite:");

        txtContaLimite.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtContaLimite.setText("0,00");
        txtContaLimite.setVerifyInputWhenFocusTarget(false);

        jLabel6.setText("Montante Min:");

        txtContaMontante.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtContaMontante.setText("0,00");

        jLabel7.setText("Deposito Min:");

        txtContaDepositoMin.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtContaDepositoMin.setText("0,00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btContaSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btContaCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbContaTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(6, 6, 6)
                                        .addComponent(txtContaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btContaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtContaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtContaMontante, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtContaDepositoMin, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtContaDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtContaLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtContaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btContaBuscar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtContaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbContaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtContaDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtContaLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtContaMontante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtContaDepositoMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btContaCancelar)
                    .addComponent(btContaSalvar))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btContaSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContaSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btContaSalvarActionPerformed

    private void btContaCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContaCancelarActionPerformed
        this.setVisible(false);
        new Main().setVisible(true);
    }//GEN-LAST:event_btContaCancelarActionPerformed

    private void cbContaTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbContaTipoItemStateChanged
        if (cbContaTipo.getSelectedItem().toString().equals(conta_corrente)) {
            jLabel3.setVisible(true);
            txtContaLimite.setVisible(true);

            jLabel6.setVisible(false);
            txtContaMontante.setVisible(false);
            jLabel7.setVisible(false);
            txtContaDepositoMin.setVisible(false);

            btContaSalvar.setEnabled(true);

        } else if (cbContaTipo.getSelectedItem().toString().equals(conta_investimento)) {
            jLabel3.setVisible(false);
            txtContaLimite.setVisible(false);

            jLabel6.setVisible(true);
            txtContaMontante.setVisible(true);
            jLabel7.setVisible(true);
            txtContaDepositoMin.setVisible(true);

            btContaSalvar.setEnabled(true);

        } else {
            Limpa();
        }
    }//GEN-LAST:event_cbContaTipoItemStateChanged

    private void btContaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContaBuscarActionPerformed
        this.setVisible(false);
        new ClientePesquisa(this.getTitle()).setVisible(true);
    }//GEN-LAST:event_btContaBuscarActionPerformed

    private void Limpa() {
        btContaSalvar.setEnabled(false);

        jLabel3.setVisible(false);
        txtContaLimite.setVisible(false);

        jLabel6.setVisible(false);
        txtContaMontante.setVisible(false);
        jLabel7.setVisible(false);
        txtContaDepositoMin.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btContaBuscar;
    private javax.swing.JButton btContaCancelar;
    private javax.swing.JButton btContaSalvar;
    private javax.swing.JComboBox cbContaTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtContaCpf;
    private javax.swing.JTextField txtContaDeposito;
    private javax.swing.JTextField txtContaDepositoMin;
    private javax.swing.JTextField txtContaLimite;
    private javax.swing.JTextField txtContaMontante;
    private javax.swing.JTextField txtContaNome;
    // End of variables declaration//GEN-END:variables
}
