/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bancoswing;

import Classes.Cliente;
import Classes.Conta;
import dao.ContaDAO;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Lemke
 */
public class ContaGerenciar extends javax.swing.JFrame {

    private final String saque = "Sacar";
    private final String deposito = "Depositar";
    private final String saldo = "Consultar Saldo";
    private final String remunera = "Remunerar";
    Cliente cliente;
    Conta conta;

    /**
     * Creates new form ContaCadastro
     */
    public ContaGerenciar(Cliente c) {
        initComponents();
        Limpa();

        if (c != null) {
            cliente = c;

            ContaDAO dao = new ContaDAO();
            conta = dao.consulta(c);

            if (conta != null) {
                txtContaGerCpf.setText(c.getCPF());
                txtContaGerNome.setText(c.getNome());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtContaGerCpf = new javax.swing.JTextField();
        btContaGerBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtContaGerNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbContaGerAcao = new javax.swing.JComboBox();
        btContaGerSalvar = new javax.swing.JButton();
        btContaGerCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtContaValor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Gerenciar Conta");
        setBounds(new java.awt.Rectangle(200, 100, 0, 0));

        jLabel4.setText("CPF:");

        btContaGerBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ic_search_black_18dp_1x.png"))); // NOI18N
        btContaGerBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContaGerBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        txtContaGerNome.setEnabled(false);

        jLabel5.setText("Ação:");

        cbContaGerAcao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Sacar", "Depositar", "Consultar Saldo", "Remunerar" }));
        cbContaGerAcao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbContaGerAcaoItemStateChanged(evt);
            }
        });

        btContaGerSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ic_save_black_18dp_1x.png"))); // NOI18N
        btContaGerSalvar.setText("Executar");
        btContaGerSalvar.setEnabled(false);
        btContaGerSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContaGerSalvarActionPerformed(evt);
            }
        });

        btContaGerCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ic_cancel_black_18dp_1x.png"))); // NOI18N
        btContaGerCancelar.setText("Cancelar");
        btContaGerCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContaGerCancelarActionPerformed(evt);
            }
        });

        jLabel2.setText("Depósito Inicial: ");

        txtContaValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtContaValor.setText("0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btContaGerSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btContaGerCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbContaGerAcao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(6, 6, 6)
                                        .addComponent(txtContaGerCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btContaGerBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtContaGerNome, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtContaValor, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtContaGerNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btContaGerBuscar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtContaGerCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbContaGerAcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtContaValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btContaGerCancelar)
                    .addComponent(btContaGerSalvar))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btContaGerSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContaGerSalvarActionPerformed
        if (cbContaGerAcao.getSelectedItem().toString().equals(saque)) {
            conta.saca(Double.parseDouble(txtContaValor.getText()));
            JOptionPane.showMessageDialog(null, "Saque bem sucedido!", "OK", JOptionPane.INFORMATION_MESSAGE);

        } else if (cbContaGerAcao.getSelectedItem().toString().equals(deposito)) {
            conta.deposita(Double.parseDouble(txtContaValor.getText()));
            JOptionPane.showMessageDialog(null, "Deposito bem sucedido!", "OK", JOptionPane.INFORMATION_MESSAGE);

        } else if (cbContaGerAcao.getSelectedItem().toString().equals(saldo)) {
            jLabel2.setText("Seu Saldo é:");
            txtContaValor.setText("" + conta.getSaldo());

        } else if (cbContaGerAcao.getSelectedItem().toString().equals(remunera)) {
            conta.remunera();
            JOptionPane.showMessageDialog(null, "Remuneração bem sucedida!", "OK", JOptionPane.INFORMATION_MESSAGE);

        }

        ContaDAO dao = new ContaDAO();
        dao.altera(conta);
    }//GEN-LAST:event_btContaGerSalvarActionPerformed

    private void btContaGerCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContaGerCancelarActionPerformed
        this.setVisible(false);
        new Main().setVisible(true);
    }//GEN-LAST:event_btContaGerCancelarActionPerformed

    private void cbContaGerAcaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbContaGerAcaoItemStateChanged
        if (cbContaGerAcao.getSelectedItem().toString().equals(saque)) {
            jLabel2.setVisible(true);
            txtContaValor.setVisible(true);
            txtContaValor.setEditable(true);

            jLabel2.setText("Valor do Saque:");
            txtContaValor.setText("0.00");

            btContaGerSalvar.setEnabled(true);

        } else if (cbContaGerAcao.getSelectedItem().toString().equals(deposito)) {
            jLabel2.setVisible(true);
            txtContaValor.setVisible(true);
            txtContaValor.setEditable(true);

            jLabel2.setText("Valor do Depósito:");
            txtContaValor.setText("0.00");

            btContaGerSalvar.setEnabled(true);

        } else if (cbContaGerAcao.getSelectedItem().toString().equals(saldo)) {
            jLabel2.setVisible(true);
            txtContaValor.setVisible(true);
            txtContaValor.setEditable(false);

            jLabel2.setText("Seu Saldo é:");

            btContaGerSalvar.setEnabled(true);

        } else if (cbContaGerAcao.getSelectedItem().toString().equals(remunera)) {
            jLabel2.setVisible(false);
            txtContaValor.setVisible(false);

            btContaGerSalvar.setEnabled(true);

        } else {
            Limpa();
        }
    }//GEN-LAST:event_cbContaGerAcaoItemStateChanged

    private void btContaGerBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContaGerBuscarActionPerformed
        this.setVisible(false);
        new ClientePesquisa(this.getTitle()).setVisible(true);
    }//GEN-LAST:event_btContaGerBuscarActionPerformed

    private void Limpa() {
        jLabel2.setVisible(false);
        txtContaValor.setVisible(false);

        btContaGerSalvar.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btContaGerBuscar;
    private javax.swing.JButton btContaGerCancelar;
    private javax.swing.JButton btContaGerSalvar;
    private javax.swing.JComboBox cbContaGerAcao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtContaGerCpf;
    private javax.swing.JTextField txtContaGerNome;
    private javax.swing.JTextField txtContaValor;
    // End of variables declaration//GEN-END:variables
}
